name: Build and publish docs

on:
  push:
    branches: [ yfm ]
  pull_request:
    branches: [ yfm ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
    - name: Install YFM
      run: npm i @doc-tools/docs -g
    - name: Build
      run: yfm --strict -i . -o ./docs-gen
    - name: Publish
      uses: nekitcorp/yandex-storage-website-action@v1
      with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.BUCKET }}
          path: "./docs-gen"
          clear: true

